import { StyleSheet } from "react-native";
import { COLORS } from "../lib/constants";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.cream,
  },
  scrollContent: {
    paddingHorizontal: 8,
    paddingTop: 12,
    paddingBottom: 80,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: COLORS.midnightNavy,
    opacity: 0.6,
  },
  filterContainer: {
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.frostGray,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  filterButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.cream,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.frostGray,
  },
  filterText: {
    flex: 1,
    fontSize: 16,
    color: COLORS.midnightNavy,
    fontWeight: "500",
  },
  clearButton: {
    padding: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "80%",
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.frostGray,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.midnightNavy,
  },
  modalCloseButton: {
    padding: 4,
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.cream,
    borderRadius: 12,
    paddingHorizontal: 12,
    margin: 16,
    borderWidth: 1,
    borderColor: COLORS.frostGray,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 16,
    color: COLORS.midnightNavy,
  },
  chapterItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.frostGray,
  },
  chapterItemText: {
    fontSize: 16,
    color: COLORS.midnightNavy,
  },
  emptyListContainer: {
    padding: 40,
    alignItems: "center",
  },
  emptyListText: {
    fontSize: 16,
    color: COLORS.midnightNavy,
    opacity: 0.6,
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 16,
    color: COLORS.midnightNavy,
    opacity: 0.6,
  },
  eventCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 4,
    marginBottom: 12,
  },
  eventImageWrapper: {
    position: "relative",
    width: "100%",
    height: 220,
    backgroundColor: COLORS.frostGray,
  },
  eventImage: {
    width: "100%",
    height: "100%",
  },
  eventImagePlaceholder: {
    alignItems: "center",
    justifyContent: "center",
  },
  eventImagePlaceholderText: {
    marginTop: 8,
    fontSize: 14,
    color: COLORS.midnightNavy,
    opacity: 0.7,
  },
  eventImageOverlay: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  eventTopRow: {
    position: "absolute",
    top: 12,
    left: 12,
    right: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  eventDateBadge: {
    width: 52,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    alignItems: "center",
    paddingVertical: 4,
  },
  eventDateMonth: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.midnightNavy,
  },
  eventDateDay: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.midnightNavy,
  },
  eventPriceBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: COLORS.crimson,
    gap: 4,
  },
  eventPriceBadgeText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.white,
  },
  eventTitleOverlay: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
  },
  eventTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.white,
    marginBottom: 4,
  },
  eventChapterText: {
    fontSize: 13,
    color: COLORS.white,
    opacity: 0.9,
  },
  eventContent: {
    padding: 14,
  },
  eventDescription: {
    fontSize: 14,
    color: COLORS.midnightNavy,
    opacity: 0.7,
    marginTop: 8,
    marginBottom: 10,
    lineHeight: 20,
  },
  eventDetails: {
    gap: 6,
  },
  eventDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  eventDetailText: {
    fontSize: 13,
    color: COLORS.midnightNavy,
    opacity: 0.75,
    flex: 1,
  },
  eventFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  eventTagPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: COLORS.cream,
    gap: 4,
  },
  eventTagText: {
    fontSize: 12,
    color: COLORS.midnightNavy,
    fontWeight: "500",
  },
  eventCtaText: {
    fontSize: 13,
    color: COLORS.crimson,
    fontWeight: "600",
  },
  ticketPrice: {
    color: COLORS.crimson,
    fontWeight: "600",
    opacity: 1,
  },
});
